trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: MSBuild@1
  inputs:
    solution: '**/src/AdventureWorks/AdventureWorks.sqlproj'
    msbuildArguments: '/t:build /p:CmdLineInMemoryStorage=True'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'src/AdventureWorks/bin/Debug/AdventureWorks.dacpac'
    ArtifactName: 'AdventureWorks'
    publishLocation: 'Container'






