# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: MSBuild@1
  inputs:
    solution: '**/src/AdventureWorks/AdventureWorks.sqlproj'
    msbuildArguments: '/t:build /p:CmdLineInMemoryStorage=True'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'src/AdventureWorks/bin/Debug/AdventureWorks.dacpac'
    ArtifactName: 'AdventureWorks'
    publishLocation: 'Container'

- task: SqlAzureDacpacDeployment@1
  inputs:
    azureSubscription: 'shasbARM'
    AuthenticationType: 'server'
    ServerName: 'shasbsql.database.windows.net'
    DatabaseName: 'shasbSQLDatabase'
    SqlUsername: 'shasb'
    SqlPassword: '$(password)'
    deployType: 'DacpacTask'
    DeploymentAction: 'Publish'
    DacpacFile: '**/src/AdventureWorks/bin/Debug/AdventureWorks.dacpac'
    IpDetectionMethod: 'AutoDetect'






